<?php

defined('ABSPATH') || exit;

function kermanentzat_legal_pages(): array
{
    $legal = kermanentzat_legal_config();
    $name = esc_html($legal['name']);
    $nif = esc_html($legal['nif']);
    $address = esc_html($legal['address']);
    $email = esc_html($legal['email']);
    $mailto = esc_url('mailto:' . $legal['email']);
    $reviewed = esc_html($legal['last_reviewed']);

    $legalEs = <<<HTML
<header class="legal-hero content-band--light"><div class="content-wrap"><span class="content-label">Información institucional</span><h1>Aviso legal</h1><p>Identidad, condiciones de uso y alcance de este sitio web.</p></div></header>
<div class="legal-layout content-band content-band--light"><div class="content-wrap legal-copy">
<section><h2>1. Titular del sitio</h2><dl class="legal-facts"><div><dt>Denominación</dt><dd>{$name}</dd></div><div><dt>NIF</dt><dd>{$nif}</dd></div><div><dt>Domicilio</dt><dd>{$address}</dd></div><div><dt>Correo electrónico</dt><dd><a href="{$mailto}">{$email}</a></dd></div><div><dt>Inscripción registral</dt><dd>Pendiente de incorporar tras comprobar la resolución o el certificado oficial.</dd></div></dl></section>
<section><h2>2. Finalidad y uso</h2><p>Este sitio informa sobre la iniciativa Egia Kermanentzat, preserva la memoria de Kerman, explica el caso y facilita formas de contacto y apoyo. La persona usuaria se compromete a utilizarlo de forma lícita y a no interferir en su funcionamiento.</p></section>
<section><h2>3. Contenidos y propiedad intelectual</h2><p>Salvo indicación distinta, los textos, el diseño y los materiales propios pertenecen a {$name} o se utilizan con autorización. No se permite su explotación comercial ni una reutilización que altere su sentido sin autorización previa. La cita y el enlace son posibles respetando autoría, contexto y legislación aplicable.</p></section>
<section><h2>4. Exactitud, disponibilidad y enlaces</h2><p>Se procura mantener la información actualizada y contrastada, pero el contenido tiene carácter informativo y no sustituye asesoramiento jurídico. El sitio puede cambiar o interrumpirse por razones técnicas. Los enlaces externos —como correo, Instagram o saretu.es— solo se abren cuando la persona visitante los activa; sus condiciones corresponden a sus respectivos responsables.</p></section>
<section><h2>5. Legislación y contacto</h2><p>Estas condiciones se interpretan conforme al Derecho español, sin perjuicio de las normas imperativas aplicables. Para comunicar errores, incidencias o usos no autorizados, escribe a <a href="{$mailto}">{$email}</a>.</p></section>
<p class="legal-review">Última revisión técnica: {$reviewed}. Texto pendiente de validación jurídica final.</p>
</div></div>
HTML;

    $legalEu = <<<HTML
<header class="legal-hero content-band--light"><div class="content-wrap"><span class="content-label">Erakundearen informazioa</span><h1>Lege-oharra</h1><p>Webgunearen nortasuna, erabilera-baldintzak eta irismena.</p></div></header>
<div class="legal-layout content-band content-band--light"><div class="content-wrap legal-copy">
<section><h2>1. Webgunearen titularra</h2><dl class="legal-facts"><div><dt>Izena</dt><dd>{$name}</dd></div><div><dt>IFK</dt><dd>{$nif}</dd></div><div><dt>Helbidea</dt><dd>{$address}</dd></div><div><dt>Posta elektronikoa</dt><dd><a href="{$mailto}">{$email}</a></dd></div><div><dt>Erregistroko inskripzioa</dt><dd>Ebazpen edo ziurtagiri ofiziala egiaztatu ondoren gehitzeko zain.</dd></div></dl></section>
<section><h2>2. Xedea eta erabilera</h2><p>Webgune honek Egia Kermanentzat ekimenari buruzko informazioa ematen du, Kermanen memoria gordetzen du, kasua azaltzen du eta harremanetarako zein laguntzarako bideak eskaintzen ditu. Erabiltzaileak webgunea legez erabiltzeko eta haren funtzionamendua ez oztopatzeko konpromisoa hartzen du.</p></section>
<section><h2>3. Edukiak eta jabetza intelektuala</h2><p>Besterik adierazi ezean, testuak, diseinua eta material propioak {$name} elkartearenak dira edo baimenarekin erabiltzen dira. Ezin dira merkataritza-helburuz ustiatu, ezta haien esanahia aldatzen duen berrerabilerarik egin ere, aldez aurreko baimenik gabe. Aipamena eta esteka egin daitezke, egiletza, testuingurua eta aplikatu beharreko legeria errespetatuz.</p></section>
<section><h2>4. Zehaztasuna, erabilgarritasuna eta estekak</h2><p>Informazioa eguneratuta eta egiaztatuta mantentzen saiatzen gara, baina edukia informatiboa da eta ez du aholkularitza juridikoa ordezten. Webgunea aldatu edo eten daiteke arrazoi teknikoengatik. Kanpoko estekak —posta, Instagram edo saretu.es— bisitariak aktibatzen dituenean baino ez dira irekitzen; haien baldintzak dagozkien arduradunenak dira.</p></section>
<section><h2>5. Legeria eta harremana</h2><p>Baldintza hauek Espainiako Zuzenbidearen arabera interpretatuko dira, aplikatu beharreko arau nahitaezkoei kalterik egin gabe. Akatsak, gorabeherak edo baimendu gabeko erabilerak jakinarazteko, idatzi <a href="{$mailto}">{$email}</a> helbidera.</p></section>
<p class="legal-review">Azken berrikuspen teknikoa: {$reviewed}. Euskarazko testua eta eduki juridikoa azken baliozkotzearen zain daude.</p>
</div></div>
HTML;

    $privacyEs = <<<HTML
<header class="legal-hero content-band--light"><div class="content-wrap"><span class="content-label">Protección de datos</span><h1>Política de privacidad</h1><p>Información por capas sobre los tratamientos reales de este proyecto.</p></div></header>
<div class="legal-layout content-band content-band--light"><div class="content-wrap legal-copy">
<section class="legal-summary" aria-labelledby="privacy-summary-es"><h2 id="privacy-summary-es">Información esencial</h2><dl class="legal-facts"><div><dt>Responsable</dt><dd>{$name}, NIF {$nif}</dd></div><div><dt>Contacto</dt><dd><a href="{$mailto}">{$email}</a></dd></div><div><dt>Finalidades</dt><dd>Responder consultas; gestionar aportaciones por transferencia y sus incidencias; administrar el sitio; y proteger su seguridad técnica.</dd></div><div><dt>Derechos</dt><dd>Acceso, rectificación, supresión, oposición, limitación y portabilidad cuando proceda.</dd></div></dl></section>
<section><h2>1. Responsable</h2><p>{$name}, con NIF {$nif} y domicilio en {$address}, es responsable de los tratamientos descritos. Puedes contactar en <a href="{$mailto}">{$email}</a>.</p></section>
<section><h2>2. Tratamientos y bases jurídicas</h2><h3>Consultas por correo</h3><p>Tratamos los datos que incluyas voluntariamente para responder, ordenar el seguimiento y acreditar la comunicación. La base será la aplicación de medidas solicitadas por ti y, según el asunto, nuestro interés legítimo en atender y documentar comunicaciones relacionadas con la actividad. Evita enviar datos sensibles o innecesarios.</p><h3>Aportaciones por transferencia</h3><p>Tratamos los datos facilitados por la entidad bancaria y los que aportes para identificar la operación, contabilizarla, cumplir obligaciones fiscales y documentales, emitir justificantes y gestionar incidencias o devoluciones. Las bases son el cumplimiento de obligaciones legales y la gestión de la aportación solicitada; cuando sea necesario, también el interés legítimo en prevenir errores o fraude.</p><h3>Registros técnicos del alojamiento</h3><p>El futuro proveedor podrá generar datos técnicos mínimos —por ejemplo, dirección IP, fecha, recurso solicitado y agente de usuario— para operar, proteger y diagnosticar el servicio. El proveedor, el detalle exacto y la conservación están pendientes de contratación y se publicarán antes de producción. La base prevista es el interés legítimo en mantener la seguridad y disponibilidad.</p><h3>Cuentas administrativas de WordPress</h3><p>Se tratarán identificadores, datos de acceso, roles y registros técnicos de un grupo restringido de personas autorizadas para publicar y mantener el sitio. La base es el interés legítimo de la asociación en administrar el canal de forma segura y, cuando corresponda, la relación contractual u organizativa con cada persona.</p></section>
<section><h2>3. Datos obligatorios y procedencia</h2><p>No hay formularios, cuentas públicas ni decisiones automatizadas. Los datos proceden de tus correos, de las transferencias iniciadas por ti, de las personas administradoras y, cuando exista hosting, de las solicitudes técnicas al servidor. Si no facilitas los datos necesarios para una consulta o incidencia, quizá no podamos atenderla.</p></section>
<section><h2>4. Destinatarios y transferencias</h2><p>Podrán acceder proveedores que presten servicios necesarios bajo contrato —alojamiento, correo, asesoría contable o técnica— y administraciones, entidades financieras, juzgados o autoridades cuando exista obligación o sea necesario para formular o defender reclamaciones. No vendemos datos. La configuración contractual de Gmail, el futuro hosting y las posibles transferencias internacionales están pendientes de verificación; se documentarán con sus garantías antes de cerrar la revisión.</p></section>
<section><h2>5. Conservación</h2><p>No fijamos plazos arbitrarios. Las consultas se conservarán mientras sean necesarias para atenderlas y defender posibles responsabilidades; la documentación de aportaciones, durante los plazos exigidos por las obligaciones contables, fiscales y legales aplicables; las cuentas, mientras exista autorización y durante el tiempo necesario para seguridad; y los logs según el plazo mínimo que se acuerde con el futuro proveedor. Después se suprimirán o bloquearán según corresponda.</p></section>
<section><h2>6. Derechos y reclamaciones</h2><p>Puedes ejercer tus derechos escribiendo a <a href="{$mailto}">{$email}</a>, indicando el derecho solicitado y la información necesaria para identificar la gestión afectada. Solo pediremos acreditación adicional si existen dudas razonables sobre la identidad. También puedes reclamar ante la <a href="https://www.aepd.es/" rel="external">Agencia Española de Protección de Datos</a>.</p></section>
<section><h2>7. Seguridad y cambios</h2><p>Aplicamos minimización, acceso restringido y medidas técnicas proporcionadas. Esta política se actualizará si cambian los tratamientos, proveedores o servicios. Cualquier servicio opcional requerirá actualizar previamente el inventario, la versión del registro y las pruebas de privacidad.</p></section>
<p class="legal-review">Última revisión técnica: {$reviewed}. Borrador informado pendiente de validación jurídica final.</p>
</div></div>
HTML;

    $privacyEu = <<<HTML
<header class="legal-hero content-band--light"><div class="content-wrap"><span class="content-label">Datuen babesa</span><h1>Pribatutasun-politika</h1><p>Proiektu honetako benetako tratamenduei buruzko geruzaz geruzako informazioa.</p></div></header>
<div class="legal-layout content-band content-band--light"><div class="content-wrap legal-copy">
<section class="legal-summary" aria-labelledby="privacy-summary-eu"><h2 id="privacy-summary-eu">Funtsezko informazioa</h2><dl class="legal-facts"><div><dt>Arduraduna</dt><dd>{$name}, IFK {$nif}</dd></div><div><dt>Harremana</dt><dd><a href="{$mailto}">{$email}</a></dd></div><div><dt>Helburuak</dt><dd>Kontsultei erantzutea; transferentzia bidezko ekarpenak eta gorabeherak kudeatzea; webgunea administratzea; eta segurtasun teknikoa babestea.</dd></div><div><dt>Eskubideak</dt><dd>Sarbidea, zuzenketa, ezabaketa, aurka egitea, mugatzea eta eramangarritasuna, bidezkoa denean.</dd></div></dl></section>
<section><h2>1. Arduraduna</h2><p>{$name}, {$nif} IFK eta {$address} helbidea duena, deskribatutako tratamenduen arduraduna da. Harremanetan jartzeko: <a href="{$mailto}">{$email}</a>.</p></section>
<section><h2>2. Tratamenduak eta oinarri juridikoak</h2><h3>Posta bidezko kontsultak</h3><p>Borondatez ematen dituzun datuak tratatzen ditugu erantzuteko, jarraipena antolatzeko eta komunikazioa egiaztatzeko. Oinarria zuk eskatutako neurriak aplikatzea izango da eta, gaiaren arabera, jarduerarekin lotutako komunikazioak artatu eta dokumentatzeko dugun interes legitimoa. Ez bidali datu sentikorrik edo beharrezkorik ez denik.</p><h3>Transferentzia bidezko ekarpenak</h3><p>Bankuak emandako datuak eta zuk eragiketa identifikatzeko, kontabilizatzeko, zerga- eta dokumentazio-betebeharrak betetzeko, egiaztagiriak emateko eta gorabeherak edo itzulketak kudeatzeko emandakoak tratatzen ditugu. Oinarriak legezko betebeharrak betetzea eta eskatutako ekarpena kudeatzea dira; beharrezkoa denean, akatsak edo iruzurra saihesteko interes legitimoa ere bai.</p><h3>Ostatuaren erregistro teknikoak</h3><p>Etorkizuneko hornitzaileak gutxieneko datu teknikoak sor ditzake —IP helbidea, data, eskatutako baliabidea eta erabiltzaile-agentea, adibidez— zerbitzua ustiatu, babestu eta diagnostikatzeko. Hornitzailea, xehetasuna eta kontserbazioa kontratatu gabe daude eta ekoizpenera igaro aurretik argitaratuko dira. Aurreikusitako oinarria segurtasuna eta erabilgarritasuna mantentzeko interes legitimoa da.</p><h3>WordPress administrazio-kontuak</h3><p>Webgunea argitaratu eta mantentzeko baimendutako pertsona talde mugatu baten identifikatzaileak, sarbide-datuak, rolak eta erregistro teknikoak tratatuko dira. Oinarria elkarteak kanala segurtasunez administratzeko duen interes legitimoa eta, hala badagokio, pertsona bakoitzarekiko kontratu- edo antolaketa-harremana da.</p></section>
<section><h2>3. Datuen jatorria eta nahitaezkotasuna</h2><p>Ez dago formulariorik, kontu publikorik edo erabaki automatizaturik. Datuak zure mezuetatik, zuk hasitako transferentzietatik, administratzaileetatik eta, hostinga dagoenean, zerbitzariari egindako eskaera teknikoetatik datoz. Kontsulta edo gorabehera baterako beharrezko datuak ematen ez badituzu, baliteke ezin erantzutea.</p></section>
<section><h2>4. Hartzaileak eta transferentziak</h2><p>Kontratupean beharrezko zerbitzuak ematen dituzten hornitzaileek —hostinga, posta, kontabilitate- edo laguntza teknikoa— eta administrazioek, finantza-erakundeek, epaitegiek edo agintariek sarbidea izan dezakete, betebeharra dagoenean edo erreklamazioak egin nahiz defendatzeko beharrezkoa denean. Ez ditugu datuak saltzen. Gmailen kontratu-konfigurazioa, etorkizuneko hostinga eta nazioarteko transferentzia posibleak egiaztatzeke daude; haien bermeak dokumentatuko dira berrikuspena itxi aurretik.</p></section>
<section><h2>5. Kontserbazioa</h2><p>Ez dugu epe arbitrariorik ezartzen. Kontsultak erantzuteko eta balizko erantzukizunak defendatzeko behar diren bitartean gordeko dira; ekarpenen dokumentazioa, aplikatu beharreko kontabilitate-, zerga- eta lege-betebeharrek eskatutako epeetan; kontuak, baimena dagoen bitartean eta segurtasunerako beharrezko denboran; eta logak, etorkizuneko hornitzailearekin adostutako gutxieneko epean. Ondoren ezabatu edo blokeatuko dira, dagokionaren arabera.</p></section>
<section><h2>6. Eskubideak eta erreklamazioak</h2><p>Eskubideak erabiltzeko, idatzi <a href="{$mailto}">{$email}</a> helbidera eta adierazi eskatutako eskubidea eta kudeaketa identifikatzeko informazioa. Nortasunari buruzko arrazoizko zalantzak badaude soilik eskatuko dugu egiaztapen gehigarria. <a href="https://www.aepd.es/" rel="external">Datuak Babesteko Espainiako Bulegoan</a> ere erreklama dezakezu.</p></section>
<section><h2>7. Segurtasuna eta aldaketak</h2><p>Datu-minimizazioa, sarbide mugatua eta neurri tekniko proportzionatuak aplikatzen ditugu. Politika eguneratuko da tratamenduak, hornitzaileak edo zerbitzuak aldatzen badira. Aukerako edozein zerbitzuk inbentarioa, erregistroaren bertsioa eta pribatutasun-probak aldez aurretik eguneratzea eskatuko du.</p></section>
<p class="legal-review">Azken berrikuspen teknikoa: {$reviewed}. Euskarazko testua eta eduki juridikoa azken baliozkotzearen zain daude.</p>
</div></div>
HTML;

    $cookiesEs = <<<HTML
<header class="legal-hero content-band--light"><div class="content-wrap"><span class="content-label">Almacenamiento y servicios</span><h1>Política de cookies</h1><p>La navegación pública actual no utiliza cookies ni almacenamiento del navegador.</p></div></header>
<div class="legal-layout content-band content-band--light"><div class="content-wrap legal-copy">
<section class="legal-summary"><h2>Resumen</h2><p>Si visitas este sitio sin iniciar sesión, no se crean cookies, no se usa <code>localStorage</code>, <code>sessionStorage</code> ni IndexedDB, y no se cargan analítica, píxeles, vídeos insertados o recursos de terceros. Por ello no se muestra un banner de consentimiento.</p></section>
<section><h2>1. Administración restringida de WordPress</h2><p>WordPress puede usar cookies técnicas únicamente cuando una persona autorizada accede al área de administración:</p><dl class="cookie-list"><div><dt><code>wordpress_test_cookie</code></dt><dd>Comprueba si el navegador admite cookies; dura la sesión.</dd></div><div><dt><code>wordpress_sec_*</code> y <code>wordpress_logged_in_*</code></dt><dd>Mantienen autenticación y seguridad de la sesión; su duración depende de la opción de inicio de sesión.</dd></div><div><dt><code>wp-settings-*</code></dt><dd>Conserva preferencias de la interfaz administrativa; WordPress define su duración técnica.</dd></div></dl><p>Estas cookies son necesarias para el acceso administrativo solicitado y no se usan en la navegación pública anónima.</p></section>
<section><h2>2. Servicios externos enlazados</h2><p>Instagram, saretu.es y el correo electrónico aparecen como enlaces. El navegador no contacta con esos proveedores al cargar nuestras páginas; solo lo hace si activas el enlace, momento en el que se aplicarán las políticas del destino.</p></section>
<section><h2>3. Cambios futuros</h2><p>El registro de servicios tiene versión 1.0.0 y no contiene servicios opcionales. Antes de incorporar analítica, publicidad, preferencias, embeds u otro servicio se deberá actualizar el inventario, determinar su base jurídica, registrar el adaptador, aumentar la versión y superar las pruebas. Solo entonces se habilitarán controles de consentimiento y almacenamiento de preferencias.</p></section>
<p class="legal-review">Última revisión técnica: {$reviewed}. Verificación jurídica final pendiente.</p>
</div></div>
HTML;

    $cookiesEu = <<<HTML
<header class="legal-hero content-band--light"><div class="content-wrap"><span class="content-label">Biltegiratzea eta zerbitzuak</span><h1>Cookie-politika</h1><p>Egungo nabigazio publikoak ez du cookierik edo nabigatzaileko biltegiratzerik erabiltzen.</p></div></header>
<div class="legal-layout content-band content-band--light"><div class="content-wrap legal-copy">
<section class="legal-summary"><h2>Laburpena</h2><p>Saioa hasi gabe webgunea bisitatzen baduzu, ez da cookierik sortzen, ez da <code>localStorage</code>, <code>sessionStorage</code> edo IndexedDB erabiltzen, eta ez da analitika, pixelik, txertatutako bideorik edo hirugarrenen baliabiderik kargatzen. Horregatik, ez da baimen-bannerrik erakusten.</p></section>
<section><h2>1. WordPressen administrazio mugatua</h2><p>WordPressek cookie teknikoak erabil ditzake baimendutako pertsona bat administrazio-eremura sartzen denean soilik:</p><dl class="cookie-list"><div><dt><code>wordpress_test_cookie</code></dt><dd>Nabigatzaileak cookieak onartzen dituen egiaztatzen du; saioak irauten du.</dd></div><div><dt><code>wordpress_sec_*</code> eta <code>wordpress_logged_in_*</code></dt><dd>Saioaren autentifikazioa eta segurtasuna mantentzen dituzte; iraupena saioa hasteko aukeraren araberakoa da.</dd></div><div><dt><code>wp-settings-*</code></dt><dd>Administrazio-interfazearen lehentasunak gordetzen ditu; WordPressek ezartzen du iraupen teknikoa.</dd></div></dl><p>Cookie horiek eskatutako administrazio-sarbiderako beharrezkoak dira eta ez dira nabigazio publiko anonimoan erabiltzen.</p></section>
<section><h2>2. Estekatutako kanpo-zerbitzuak</h2><p>Instagram, saretu.es eta posta elektronikoa esteka gisa ageri dira. Nabigatzailea ez da hornitzaile horiekin harremanetan jartzen gure orriak kargatzean; esteka aktibatzen baduzu soilik egingo du, eta orduan helmugako politikak aplikatuko dira.</p></section>
<section><h2>3. Etorkizuneko aldaketak</h2><p>Zerbitzuen erregistroak 1.0.0 bertsioa du eta ez dauka aukerako zerbitzurik. Analitika, publizitatea, lehentasunak, embedak edo beste zerbitzu bat gehitu aurretik, inbentarioa eguneratu, oinarri juridikoa zehaztu, egokigailua erregistratu, bertsioa handitu eta probak gainditu beharko dira. Orduan soilik gaituko dira baimen-kontrolak eta lehentasunen biltegiratzea.</p></section>
<p class="legal-review">Azken berrikuspen teknikoa: {$reviewed}. Euskarazko testua eta eduki juridikoa azken baliozkotzearen zain daude.</p>
</div></div>
HTML;

    return [
        'es' => ['legal' => $legalEs, 'privacy' => $privacyEs, 'cookies' => $cookiesEs],
        'eu' => ['legal' => $legalEu, 'privacy' => $privacyEu, 'cookies' => $cookiesEu],
    ];
}

